MAX_EMAIL: int = 254
MAX_NAME: int = 150
MAX_TAG: int = 32
MAX_INGREDIENT: int = 128
MAX_UNIT: int = 64
RECIPE_MAX_FIELDS: int = 256
SHORT_LINK_LENGTH: int = 3
PAGE_SIZE: int = 6
CSV_HEADERS: list = ['Ингредиент', 'Количество', 'Единица измерения']
FILE_BEGIN: int = 0
MIN_COOKING_TIME: int = 0
MIN_AMOUNT: int = 1
EMPTY_VALUES = (None, "", [], (), {})
