volumes:
  static:
  media:
  pg_data:

services:

  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    image: hihix/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db

  frontend:
    container_name: foodgram-frontend
    image: hihix/foodgram_frontend
    command: cp -r /app/build/. /app/static/
    volumes:
      - static:/app/static

  nginx:
    container_name: foodgram-proxy
    image: hihix/foodgram_nginx
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - 8000:80