version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    image: hihix/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    container_name: foodgram-front
    image: hihix/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/frontend_static

  nginx:
    image: hihix/foodgram_gateway
    volumes:
      - static:/staticfiles
      - media:/media
    ports:
      - 8000:80