# Generated by Django 4.2.15 on 2024-09-15 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriterecipe',
            name='id',
        ),
        migrations.RemoveField(
            model_name='favoriterecipe',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='favoriterecipe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.CreateModel(
            name='BaseUserRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='baseuserrecipe_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.baseuserrecipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='baseuserrecipe_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.baseuserrecipe'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='baseuserrecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe'),
        ),
    ]
